name: Build PSPRO-linux

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y wget unzip build-essential git

    - name: Download PS5 Payload SDK
      run: |
        sudo wget -O /tmp/sdk.zip \
        https://github.com/ps5-payload-dev/sdk/releases/download/v0.34/ps5-payload-sdk.zip

        sudo unzip /tmp/sdk.zip -d /opt

    - name: Clone repo
      run: |
        git clone https://github.com/br3akthescr1pt/PSPRO-linux repo

    - name: Build
      run: |
        cd repo
        export PS5_PAYLOAD_SDK=/opt/ps5-payload-sdk
        make

    - name: Show output (debug)
      run: |
        ls -R repo

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PSPRO-linux-build
        path: repo/**/*.elf
